### ISSUE TITLE
顧客登録の際の管理者対応づけ

### ISSUE THREAD

**Issue by rnasakazu** [interfirm/rails-tutorial-2020#3]
**対応の背景・理由**
顧客と管理者の紐付けを固定で行なっていたため
顧客と管理の紐づけを変更できるようにする

**対応した内容**
パラメータを用いて顧客と管理を紐付けする

**動作確認方法**
`http://localhost:3000/rooms/enter?chat_id=1`
chat_id: 管理者のid

<img width="1130" alt="動作画面" src="https://user-images.githubusercontent.com/45251394/77322887-c2712a00-6d57-11ea-9971-09c60e0ea09d.png">

**Comment by rnasakazu** [comment]
- [ ] パラメータから管理者と顧客のチャットルームを作成する。

**現状**
Admin.firstと紐付けを行なっている

**ゴール**
顧客のチャットルームにパラメータを用いて管理者と紐づける

**Comment by rnasakazu** [comment]
**対応の背景・理由**
顧客と管理者の紐付けを固定で行なっていたため
顧客と管理の紐づけを変更できるようにする

**対応した内容**
パラメータを用いて顧客と管理を紐付けする

**動作確認方法**
`http://localhost:3000/rooms/enter?chat_id=1`
chat_id: 管理者のid

<img width="1130" alt="動作画面" src="https://user-images.githubusercontent.com/45251394/77322887-c2712a00-6d57-11ea-9971-09c60e0ea09d.png">

**Comment by kazumaGOGO** [comment]
@rnasakazu 
チャットアプリケーションを使うユーザーは`chat_id`パラメータに適切な値をセットしなくてはいけないということですよね？
どういったロジックで`chat_id`をセットするイメージですか？

**Comment by rnasakazu** [comment]
@kazumaGOGO 
申し訳ないです。
最終的にはscript埋め込みで呼び出すことから、埋め込む際にidを付与しようと考えていました。
そのため、現状パラメータから紐付けを行っています。
<img width="1680" alt="script埋め込み" src="https://user-images.githubusercontent.com/45251394/77422132-5272aa80-6e10-11ea-9c3a-24835c1063ba.png">

**Comment by kazumaGOGO** [comment]
@rnasakazu 
なるほど、チャモを参考に、Chatアプリケーションを呼ぶJSタグ内で、適切な`chat_id`をAPI経由で取得し、パラメータにセットする、ということですよね？

事前に`chat_id`のパラメータをセットすることが必須である理由が分かっていないのですが、パラメータを渡さないとどういった問題が起こりますか？

**Comment by rnasakazu** [comment]
@kazumaGOGO 
Chatアプリケーションを呼ぶJSタグ内でchat_idがわかればパラメータにセットする必要はなくなりますね。
JSタグ内でchat_idを設定する代替手段として一時的にパラメータからの紐付けにしています。

**Comment by kazumaGOGO** [comment]
@rnasakazu 
いえ、 chat_id の指定が無くても大丈夫ではないですか？
事前にAPI経由で管理者を取得してパラメータで渡すのではなく、以下の様にバックエンド側で管理者を決めるのではダメですか？

1. http://localhost:3000/rooms/enter を開いてチャットが開始される
1. システム側のロジックで、ユーザーの対応を行う管理者を決定する
1. Customer と Admin を紐付けるためのデータを登録する
1. チャットが開始される

**Comment by rnasakazu** [comment]
@kazumaGOGO 
バックエンド側で管理者を決めるっていうのは紐付け先を固定するということでいいですか？
複数のサービスで使えるようにするには、紐付けができるようにしておいた方がいいと考えて固定しない方向で考えていました。

**Comment by kazumaGOGO** [comment]
@rnasakazu 
> バックエンド側で管理者を決めるっていうのは紐付け先を固定するということでいいですか？

固定にしなくても良いかなと思っています。
例えば、「全ての管理者が均等な負荷になる様、管理者を動的に決める」という方法もあるかと思ったのですが、難しいですか？

事前にAPIで管理者を取得出来るのであれば、チャットが開始するタイミングでも管理者を決められるかと思っているのですが。

**Comment by rnasakazu** [comment]
@kazumaGOGO 
すいません、そこまでは考えてなかったです...
考えていたのは、例えばなんですけど
バイク比較とすまっぴーとで、管理者を分けるということを考えていました。

**Comment by kazumaGOGO** [comment]
@rnasakazu 
なるほど〜、通常、チャットの対応をするオペレータ的な役割をする人は複数人居るので、いい感じに担当を割り振る様な仕組みにしておく方が使いやすいかと思います！

> バイク比較とすまっぴーとで、管理者を分けるということを考えていました。

もし、そういった用途であれば、接続元URLのドメイン名で管理者を割り振れば良いので、`chat_id`の様なクエリーパラメータは無くて問題ないかと思いますよ。

**Comment by rnasakazu** [comment]
@kazumaGOGO 
かしこまりました。
接続元URLドメイン、かしこまりました。

仕様変更いたします！

**Comment by kazumaGOGO** [comment]
@rnasakazu 
はい、宜しくお願い致します！
今回は、シンプルに Admins テーブルの中から1レコードをランダムで取得し、それと紐付ける仕様で良いかと思います。
