### ISSUE TITLE
新着通知

### ISSUE THREAD

**Issue by rnasakazu** [interfirm/rails-tutorial-2020#8]
**したいこと**
メッセージが来たことをわかりやすくする。

管理画面
　未読メッセージ数を表記

顧客画面
　新着バッジを付加

**対応の背景・理由**
未読メッセージがあるかをわかりやすくする

**対応した内容**
Admin：未読メッセージがあるルームのtimestampを赤く
           　開いているルーム以外のメッセージを受信した際にもtimestampを赤くする
Customer：未読メッセージがあればチャットウィンドウにnewを表示する
                　チャットウィンドウが閉じている時にメッセージを受信した際にもnewを表示する

**動作確認方法**
`http://localhost:3000/admins/rooms`にアクセスし
別ブラウザで
`http://localhost:3000/rooms/enter?chat_id=1`にアクセス

それぞれメッセージを送信する

Admin
<img width="1470" alt="動作確認_Admin" src="https://user-images.githubusercontent.com/45251394/77324847-b6d33280-6d5a-11ea-99bd-eb5dd4363ce8.png">

Customer
<img width="1130" alt="動作確認_Customer" src="https://user-images.githubusercontent.com/45251394/77324867-bc307d00-6d5a-11ea-9b94-6db52064ada8.png">

**Comment by rnasakazu** [comment]
**対応の背景・理由**
未読メッセージがあるかをわかりやすくする

**対応した内容**
Admin：未読メッセージがあるルームのtimestampを赤く
           　開いているルーム以外のメッセージを受信した際にもtimestampを赤くする
Customer：未読メッセージがあればチャットウィンドウにnewを表示する
                　チャットウィンドウが閉じている時にメッセージを受信した際にもnewを表示する

**動作確認方法**
`http://localhost:3000/admins/rooms`にアクセスし
別ブラウザで
`http://localhost:3000/rooms/enter?chat_id=1`にアクセス

それぞれメッセージを送信する

<img width="1470" alt="動作確認_Admin" src="https://user-images.githubusercontent.com/45251394/77324847-b6d33280-6d5a-11ea-99bd-eb5dd4363ce8.png">

<img width="1130" alt="動作確認_Customer" src="https://user-images.githubusercontent.com/45251394/77324867-bc307d00-6d5a-11ea-9b94-6db52064ada8.png">

**Comment by kazumaGOGO** [comment]
@rnasakazu 
以下のRoom一覧の表示はリアルタイムで更新されない仕様ですよね？
http://localhost:3000/admins/rooms

Room一覧のリアルタイム更新の実装は難しかったですか？

**Comment by kazumaGOGO** [comment]
@rnasakazu すみません、ローカルのコードが古い状態でした。↑は無視して下さい :pray:
